name: "Update NH"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - uses: actions/checkout@v3
      name: Checkout

    - run: nix profile install --inputs-from . nixpkgs#cargo-bump nixpkgs#cargo
      name: Install dependencies

    - run: |
        cargo bump minor
        cargo update
      name: Bump

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: '${{ secrets.PAT }}'
        title: 'build: bump deps'
        commit-message: |
          Bump all deps


          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: GitHub <noreply@github.com>
        branch: update
        branch-suffix: timestamp
        delete-branch: true
